# Generated by Django 6.1 on 2026-08-31 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='products/brands/')),
                ('origin_country', models.CharField(default='India', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('icon', models.CharField(default='bi-gear-wide-connected', help_text='Bootstrap Icon class name', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/categories/')),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price (₹)', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Discounted Selling Price (₹)', max_digits=10)),
                ('discount_percentage', models.PositiveIntegerField(default=0, help_text='Calculated automatically or manual override')),
                ('stock', models.PositiveIntegerField(default=25)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=12)),
                ('warranty', models.CharField(default='1 Year Manufacturer Warranty', max_length=100)),
                ('is_universal', models.BooleanField(default=False, help_text='Fits all standard vehicles')),
                ('is_3d_part', models.BooleanField(default=False, help_text='Can be configured in 3D Customizer')),
                ('part_type', models.CharField(blank=True, choices=[('paint', 'Paint Option'), ('wheels', 'Wheel / Rim'), ('tyres', 'Tyre'), ('bumper_front', 'Front Bumper'), ('bumper_rear', 'Rear Bumper'), ('spoiler', 'Rear Spoiler'), ('side_skirt', 'Side Skirts'), ('diffuser', 'Rear Diffuser'), ('grille', 'Front Grille'), ('headlight', 'Headlight Set'), ('taillight', 'Tail Light Set'), ('exhaust', 'Performance Exhaust'), ('interior', 'Interior Trim')], help_text='3D customizer part slot if applicable', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productbrand')),
            ],
            options={
                'ordering': ['-featured', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_notes', models.CharField(blank=True, help_text='e.g. All variants or Petrol DCT only', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='products.product')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_parts', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Product Compatibilities',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('image_type', models.CharField(choices=[('primary', 'Primary Display Image'), ('gallery', 'Gallery Image'), ('thumbnail', 'Thumbnail'), ('detail', 'Detailed View'), ('installed', 'Installed Preview')], default='gallery', max_length=30)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'brand'], name='products_pr_categor_1e5c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price', 'rating'], name='products_pr_price_bb796d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcompatibility',
            unique_together={('product', 'vehicle')},
        ),
    ]
