# Generated by Django 6.1 on 2026-08-31 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('vehicles', '0002_alter_vehicleimage_options_vehicleimage_license_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='installed_vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehicle featured in installed preview', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_product_previews', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='license_info',
            field=models.CharField(default='Authorized Distributor Cleared License', help_text='Licensing terms or rights status', max_length=200),
        ),
        migrations.AddField(
            model_name='productimage',
            name='license_status',
            field=models.CharField(choices=[('VALID', 'Valid & Cleared'), ('LICENSE_REQUIRED', 'License Required'), ('PROPRIETARY', 'Proprietary OEM Asset'), ('EDITORIAL', 'Editorial Use Only')], default='VALID', max_length=30),
        ),
        migrations.AddField(
            model_name='productimage',
            name='source',
            field=models.CharField(default='Car Delights Automotive Engineering Media', help_text='e.g. Manufacturer Direct, Brembo OEM, Michelin Media Studio', max_length=150),
        ),
        migrations.AddField(
            model_name='productimage',
            name='source_url',
            field=models.URLField(blank=True, help_text='Official asset repository link', null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('primary', 'Primary Display Image'), ('front', 'Front Perspective View'), ('side', 'Side Profile View'), ('detail', 'Detailed Close-up & Texture'), ('packaging', 'Genuine OEM Packaging'), ('installed', 'Installed on Vehicle Example'), ('schematic', 'Technical Blueprint & Schematics'), ('gallery', 'General Gallery Image')], default='gallery', max_length=30),
        ),
    ]
