# Generated by Django 6.1 on 2026-08-31 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('coupon_code', models.CharField(help_text='e.g. TATA20, DELIGHT500', max_length=50, unique=True)),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage (%) Off'), ('fixed', 'Flat Amount (₹) Off')], default='percentage', max_length=20)),
                ('discount_percentage', models.PositiveIntegerField(default=0, help_text='Percentage discount e.g. 15 for 15%')),
                ('fixed_discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed amount discount in ₹', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum cap in ₹', max_digits=10, null=True)),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order value in ₹', max_digits=10)),
                ('section', models.CharField(choices=[('daily', 'Daily Deals'), ('weekend', 'Weekend Specials'), ('festival', 'Festival Bonanza'), ('tata', 'Tata Owners Special'), ('tyres', 'Tyre Deals'), ('services', 'Service & Care Offers'), ('accessories', 'Accessories Discounts')], default='daily', max_length=30)),
                ('badge_text', models.CharField(default='Special Offer', max_length=50)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='offers/banners/')),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['section', '-created_at'],
            },
        ),
    ]
