# Generated by Django 6.1 on 2026-08-31 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text='e.g. Daily Commuter, Weekend Rocket', max_length=100)),
                ('registration_number', models.CharField(blank=True, help_text='e.g. MH 02 CD 9999', max_length=20)),
                ('purchase_year', models.PositiveIntegerField(default=2024)),
                ('current_mileage', models.PositiveIntegerField(default=15000, help_text='Mileage in km')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_vehicles', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_users', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
