# Generated by Django 6.1 on 2026-08-31 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in ₹ INR', max_digits=10)),
                ('duration', models.CharField(default='60 mins', help_text='e.g. 45 mins, 2 hours, 1 day', max_length=50)),
                ('features', models.TextField(help_text='Newline-separated list of included features')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/gallery/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('booking_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', '-is_featured', 'price'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='bi-wrench-adjustable', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=40, unique=True)),
                ('vehicle_custom_name', models.CharField(blank=True, help_text='e.g. Hyundai Creta 2025', max_length=150)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(help_text='e.g. 10:00 AM - 12:00 PM', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('pincode', models.CharField(default='400001', max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Booking Received'), ('Confirmed', 'Slot Confirmed'), ('Technician Assigned', 'Technician Assigned'), ('In Progress', 'Service In Progress'), ('Completed', 'Service Completed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=40)),
                ('technician_name', models.CharField(default='Rahul Sharma (Lead Specialist)', max_length=100)),
                ('technician_phone', models.CharField(default='+91 98765 12345', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-booking_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
        ),
    ]
