# Generated by Django 6.1 on 2026-08-31 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('finish_type', models.CharField(choices=[('Solid', 'Solid Finish'), ('Metallic', 'Metallic High-Gloss'), ('Pearl', 'Deep Pearl Coat'), ('Matte', 'Matte Stealth Finish'), ('Satin', 'Satin Silk Finish'), ('Gloss', 'Ultra Gloss'), ('Chrome', 'Mirror Chrome / Liquid Metal'), ('Two-tone', 'Two-Tone Dual Coat')], default='Metallic', max_length=50)),
                ('hex_color', models.CharField(help_text='e.g. #0B192C', max_length=7)),
                ('secondary_hex_color', models.CharField(blank=True, help_text='For two-tone paints e.g. #111111', max_length=7, null=True)),
                ('roughness', models.FloatField(default=0.2, help_text='0.0 (smooth) to 1.0 (rough)')),
                ('metalness', models.FloatField(default=0.8, help_text='0.0 (dielectric) to 1.0 (metal)')),
                ('clearcoat', models.FloatField(default=1.0, help_text='Clearcoat intensity')),
                ('clearcoat_roughness', models.FloatField(default=0.05)),
                ('price', models.DecimalField(decimal_places=2, default=25000.0, help_text='Custom paint job price (₹)', max_digits=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='customization/paints/')),
            ],
            options={
                'ordering': ['finish_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(default='Custom Dream Build', max_length=150)),
                ('installation_fee', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('snapshot_image', models.TextField(blank=True, help_text='Base64 or image URL thumbnail of build')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bumper_front', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_bumper_front', to='products.product')),
                ('bumper_rear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_bumper_rear', to='products.product')),
                ('diffuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_diffuser', to='products.product')),
                ('exhaust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_exhaust', to='products.product')),
                ('grille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_grille', to='products.product')),
                ('headlights', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_headlights', to='products.product')),
                ('interior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_interior', to='products.product')),
                ('side_skirt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_side_skirt', to='products.product')),
                ('spoiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_spoiler', to='products.product')),
                ('taillights', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_taillights', to='products.product')),
                ('tyre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_tyre', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_builds', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_builds', to='vehicles.vehicle')),
                ('wheel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_wheel', to='products.product')),
                ('paint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customization.paintoption')),
            ],
        ),
    ]
