# Generated by Django 6.1 on 2026-08-31 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vehicles/brands/')),
                ('origin_country', models.CharField(default='India', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=150)),
                ('variant', models.CharField(blank=True, default='Standard', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('body_type', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('XUV', 'XUV'), ('MUV', 'MUV'), ('MPV', 'MPV'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Luxury', 'Luxury'), ('Sports', 'Sports'), ('EV', 'Electric Vehicle (EV)')], default='SUV', max_length=50)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('CNG', 'CNG')], default='Petrol', max_length=50)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('DCT', 'Dual Clutch (DCT/DSG)'), ('CVT', 'Continuously Variable (CVT)'), ('iMT', 'Intelligent Manual (iMT)'), ('EV-Direct', 'Direct Drive (EV)')], default='Manual', max_length=50)),
                ('engine', models.CharField(help_text='e.g. 1.5L Turbo GDi', max_length=150)),
                ('engine_capacity', models.CharField(help_text='e.g. 1482 cc or 60 kWh', max_length=100)),
                ('power', models.CharField(help_text='e.g. 160 PS @ 5500 rpm', max_length=100)),
                ('torque', models.CharField(help_text='e.g. 253 Nm @ 1500-3500 rpm', max_length=100)),
                ('seating', models.PositiveIntegerField(default=5)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR (₹)', max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_3d_available', models.BooleanField(default=False)),
                ('model_3d_path', models.CharField(blank=True, help_text='Relative or media path to 3D asset (.glb/.gltf)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.brand')),
            ],
            options={
                'ordering': ['-featured', 'brand__name', 'model', 'year'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_slug', models.CharField(help_text='Product category slug compatible with this vehicle', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_records', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/gallery/')),
                ('image_type', models.CharField(choices=[('thumbnail', 'Thumbnail'), ('front', 'Front View'), ('rear', 'Rear View'), ('side', 'Side View'), ('interior', 'Interior'), ('dashboard', 'Dashboard'), ('gallery', 'Gallery')], default='gallery', max_length=50)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='General', help_text='e.g. Dimensions, Engine, Brakes, Safety', max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='VehicleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('transmission', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('features', models.TextField(blank=True, help_text='Comma-separated or bullet list of exclusive features')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='vehicles.vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['brand', 'model'], name='vehicles_ve_brand_i_de8e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['body_type', 'fuel_type'], name='vehicles_ve_body_ty_815499_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['price'], name='vehicles_ve_price_da359f_idx'),
        ),
    ]
