# Generated by Django 6.1 on 2026-08-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['-is_primary', 'sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='license_info',
            field=models.CharField(default='Commercial & Editorial License Cleared', help_text='Licensing terms or rights status', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='license_status',
            field=models.CharField(choices=[('VALID', 'Valid & Cleared'), ('LICENSE_REQUIRED', 'License Required'), ('PROPRIETARY', 'Proprietary OEM Asset'), ('EDITORIAL', 'Editorial Use Only')], default='VALID', max_length=30),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='source',
            field=models.CharField(default='Car Delights Automotive Media Lab', help_text='e.g. OEM Studio Press, Manufacturer Media, Car Delights Studio', max_length=150),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='source_url',
            field=models.URLField(blank=True, help_text='Official origin or asset repository link', null=True),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image_type',
            field=models.CharField(choices=[('thumbnail', 'Thumbnail'), ('front', 'Front View'), ('rear', 'Rear View'), ('side', 'Side View'), ('interior', 'Interior Cockpit'), ('dashboard', 'Dashboard & Infotainment'), ('gallery', 'Gallery View')], default='gallery', max_length=50),
        ),
    ]
