# Generated by Django 6.1 on 2026-08-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicleimage_options_vehicleimage_license_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimage',
            name='license',
            field=models.CharField(default='Commercial & Editorial License Cleared', help_text='Licensing terms or rights status', max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='vehicles/photos/'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image_type',
            field=models.CharField(choices=[('front_three_quarter', 'Front Three-Quarter View'), ('rear_three_quarter', 'Rear Three-Quarter View'), ('front', 'Front View'), ('rear', 'Rear View'), ('side', 'Side Profile View'), ('interior', 'Interior Cockpit'), ('dashboard', 'Dashboard & Infotainment'), ('gallery', 'Gallery View'), ('thumbnail', 'Thumbnail')], default='front_three_quarter', max_length=50),
        ),
    ]
