# Generated by Django 6.1 on 2026-09-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicleimage_license_alter_vehicleimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimage',
            name='license_url',
            field=models.URLField(blank=True, help_text='Licensing terms documentation URL', null=True),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image_type',
            field=models.CharField(choices=[('front', 'Front View'), ('front_three_quarter', 'Front Three-Quarter View'), ('side', 'Side Profile View'), ('rear', 'Rear View'), ('rear_three_quarter', 'Rear Three-Quarter View'), ('interior', 'Interior Cockpit'), ('dashboard', 'Dashboard & Infotainment'), ('gallery', 'Gallery View')], default='front_three_quarter', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='license_status',
            field=models.CharField(choices=[('REAL_PHOTO', 'Real Photograph (Approved)'), ('VALID', 'Valid & Cleared'), ('PROPRIETARY', 'Proprietary OEM Asset'), ('EDITORIAL', 'Editorial Use Only'), ('LICENSE_REQUIRED', 'License Required'), ('MISSING', 'Missing Photograph'), ('DUPLICATE', 'Duplicate Assignment'), ('BROKEN', 'Broken File'), ('PENDING_REVIEW', 'Pending Review')], default='REAL_PHOTO', max_length=30),
        ),
    ]
