# Generated by Django 6.1 on 2026-09-01 06:14

import apps.vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicleimage_license_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Image pixel height', null=True),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, help_text='MD5 perceptual image hash', max_length=64),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='verified',
            field=models.BooleanField(db_index=True, default=True, help_text='Verified real photograph'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Image pixel width', null=True),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to=apps.vehicles.models.vehicle_image_upload_path),
        ),
        migrations.AddIndex(
            model_name='vehicleimage',
            index=models.Index(fields=['vehicle', 'is_primary'], name='vehicles_ve_vehicle_059fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleimage',
            index=models.Index(fields=['image_hash'], name='vehicles_ve_image_h_ecf5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleimage',
            index=models.Index(fields=['verified'], name='vehicles_ve_verifie_65a3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleimage',
            index=models.Index(fields=['license_status'], name='vehicles_ve_license_c49bfa_idx'),
        ),
    ]
